version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pAHkZSWxxm
      MYSQL_DATABASE: sql10664983
      MYSQL_USER: sql10664983
      MYSQL_PASSWORD: pAHkZSWxxm
    networks:
      - mynetwork

  node:
    image: node:latest
    container_name: node-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DEV: "false"
      DB_HOST: "mysql"
      DB_USERNAME: "sql10664983"
      DB_PASSWORD: "pAHkZSWxxm"
      DB_DATABASE: "sql10664983"
    command: 
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
        npm start
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
